/*************************************************************************
 *
 * CAUTION:  DO NOT EDIT THIS FILE -- YOUR CHANGES WILL BE LOST!
 *
 * This file is generated by config.sh
 *
 *************************************************************************/

#define REALM_VERSION "0.89.0"

#define REALM_INSTALL_PREFIX      "/usr/local"
#define REALM_INSTALL_EXEC_PREFIX "/usr/local"
#define REALM_INSTALL_INCLUDEDIR  "/usr/local/include"
#define REALM_INSTALL_BINDIR      "/usr/local/bin"
#define REALM_INSTALL_LIBDIR      "/usr/local/lib"
#define REALM_INSTALL_LIBEXECDIR  "/usr/local/libexec"

#ifdef REALM_DEBUG
#  define REALM_MAX_BPNODE_SIZE 1000
#else
#  define REALM_MAX_BPNODE_SIZE 1000
#endif

#if 1
#  define REALM_ENABLE_REPLICATION 1
#endif

#if 0
#  define REALM_ENABLE_ALLOC_SET_ZERO 1
#endif

#if 1
#  define REALM_ENABLE_ENCRYPTION 1
#endif

#if 1
#  define REALM_ENABLE_ASSERTIONS 1
#endif
