name: Build and cache executor
description: Once supplied build commands, the action checks for cached binaries and builds if not found. The outcome of a build is then cached for later use
inputs:
  cmds:
    description: Command that needs to be executed to produce the build
    required: true
  cachePath:
    description: Path that the action is going to use to produce an index to look up cached artifacts or to save them if none were found
    required: true
outputs:
  hashKey:
    description: Key used to retrieve the just cached build at a later time
runs:
  using: node12
  main: ./dist/index.js
