FROM ubuntu:trusty

RUN apt-get update && \
    apt-get install -y build-essential libssl-dev python-cheetah pkg-config xutils-dev software-properties-common \
                       libboost-dev libasio-dev libyaml-cpp-dev && \
    add-apt-repository -y ppa:ubuntu-toolchain-r/test && apt-get update && apt-get install -y gcc-4.9 g++-4.9 && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9

ADD https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh /cmake-3.7.2-Linux-x86_64.sh
RUN sh /cmake-3.7.2-Linux-x86_64.sh --prefix=/ --skip-license