name: 'Run Android tests on Device Farm'
inputs:
  apk-path:
    required: true
  app-id:
    required: true
  project-arn:
    required: true
  device-pool-arn:
    required: true
  arguments:
    default: _
outputs:
  test-results-path:
    value: ${{ steps.get-test-results.outputs.results-path }}
runs:
  using: "composite"
  steps:
    - name: Run the tests
      uses: realm/aws-devicefarm/test-application@d94e739490340474f8464f74289a0f48706dd3a3
      id: run-tests
      with:
        project_arn: ${{ inputs.project-arn}}
        device_pool_arn: ${{ inputs.device-pool-arn }}
        app_file: ${{ inputs.apk-path }}
        app_type: ANDROID_APP
        test_type: APPIUM_PYTHON
        test_package_file: https://github.com/realm/aws-devicefarm-sample-data/releases/download/0.3/sample_env_python3.zip
        test_package_type: APPIUM_PYTHON_TEST_PACKAGE
        test_spec_file: test_spec-${{ inputs.app-id }}.yaml
        test_spec_type: APPIUM_PYTHON_TEST_SPEC
        remote_src: true
        test_spec: |
          version: 0.1
          phases:
            install:
              commands:
                - export PYTHON_VERSION=3
            pre_test:
              commands:
                - adb -s $DEVICEFARM_DEVICE_UDID shell pm grant ${{ inputs.app-id }} android.permission.READ_EXTERNAL_STORAGE
                - adb -s $DEVICEFARM_DEVICE_UDID shell pm grant ${{ inputs.app-id }} android.permission.WRITE_EXTERNAL_STORAGE
                - adb -s $DEVICEFARM_DEVICE_UDID shell mkdir /storage/emulated/0/Documents
            test:
              commands:
                - adb -s $DEVICEFARM_DEVICE_UDID shell am instrument -w -r ${{ inputs.arguments != '_' && format('-e args \"{0}\"', inputs.arguments) || '' }} ${{ inputs.app-id }}/.TestRunner
            post_test:
              commands:
                - adb -s $DEVICEFARM_DEVICE_UDID pull /storage/emulated/0/Documents/TestResults.Android.xml $DEVICEFARM_LOG_DIR/TestResults.Android.xml
          artifacts:
            - $DEVICEFARM_LOG_DIR
        file_artifacts: |
          Customer Artifacts.zip
    - run: |
        Expand-Archive 'Customer Artifacts.zip' -DestinationPath artifacts
        echo '::set-output name=results-path::${{ github.workspace }}/artifacts/Host_Machine_Files/$DEVICEFARM_LOG_DIR/TestResults.Android.xml'
      name: Fetch test artifacts
      shell: pwsh
      id: get-test-results
    - run: |
        echo "::group::Data"
        echo (ConvertFrom-Json '${{ steps.run-tests.outputs.data }}' | ConvertTo-Json)
        echo "::endgroup::"
        Import-Module AWSPowerShell
        $jobs = Get-DFJobList -Arn ${{ steps.run-tests.outputs.arn }}
        $suites = Get-DFSuiteList -Arn $jobs[0].Arn
        $artifacts = Get-DFArtifactList -Arn $suites[1].Arn -Type File | Where-Object { $_.Name -EQ "Logcat" }
        echo "::group::Logcat"
        Invoke-WebRequest -Uri $artifacts[0].Url | Select-Object -Expand RawContent
        echo "::endgroup::"
      shell: pwsh
      if: always()
      name: Device Farm Output
