name: android-docker-container-build
description: Spawn a debian docker container and linux build wrappers
runs:
  using: docker
  # this won't work, search how to
  image: ../../../wrappers/android.Dockerfile
