name: 'Build macos wrapper'
description: 'Builds macos wrapper for .net5'
inputs:
  cmds:
    description: "Commands that need to be executed. It's a JSON array of object cmdObj => { \"cmd\": \"your-cmd\", \"cmdParams\": [\"str1, ..., strN\"]}"
    required: true
  cachePaths:
    description: List of space separated paths that the action is going to use as an index to look for cached artifacts.
    required: true
runs:
  using: 'node12'
  main: './dist/index.js'
