name: 'Build macos wrapper'
description: 'Builds macos wrapper for .net5'
inputs:
  cmd-array:
    description: 'Needed commands to make your build'
    required: true
runs:
  # using: "composite"
  # steps:
    # - name: 'Build wrappers'
      # run: REALM_CMAKE_CONFIGURATION=${{ inputs.build-configuration }} ./wrappers/build-macos.sh
      # shell: bash
  using: 'node12'
  main: './dist/index.js'
