////////////////////////////////////////////////////////////////////////////
//
// Copyright 2016 Realm Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
////////////////////////////////////////////////////////////////////////////

using System;

namespace Realms.Sync
{
    /// <summary>
    /// Objects of this class are used to offer permissions to owned Realms.
    /// They are created exclusively by the client and are processed by the server
    /// as indicated by the status fields.
    /// </summary>
    /// <remarks>
    /// When offering permissions, you should create the offer and add it to the <see cref="User"/>'s Management Realm.
    /// Then you can subscribe to <see cref="RealmObject.PropertyChanged"/> to be notified when the server has processed the request.
    /// Once the request has been processed, the <see cref="ObjectStatus"/> and <see cref="StatusCode"/> will be updated accordingly.
    /// If the request has been processed successfully, the <see cref="Token"/> will be populated and you can share it with users you wish to grant permissions to.
    /// If the request has failed, the <see cref="StatusMessage"/> will be updated with relevant information about the failure and <see cref="StatusCode"/> will be set to a non-zero value.
    /// </remarks>
    public class PermissionOffer : RealmObject, IPermissionObject
    {
        /// <inheritdoc />
        public string Id { get; }

        /// <inheritdoc />
        public DateTimeOffset CreatedAt { get; }

        /// <inheritdoc />
        public DateTimeOffset UpdatedAt { get; }

        /// <inheritdoc />
        public int? StatusCode { get; }

        /// <inheritdoc />
        public string StatusMessage { get; }

        /// <inheritdoc />
        public ManagementObjectStatus ObjectStatus { get; }

        /// <summary>
        /// Gets the token that can be used to offer the permissions defined in this object to another user.
        /// </summary>
        /// <remarks>
        /// This is generated by the server upon successful processing of the request.
        /// </remarks>
        public string Token { get; }

        /// <summary>
        /// Gets the url of the Realm to offer permissions to.
        /// </summary>
        public string RealmUrl { get; }

        /// <summary>
        /// Gets a value indicating whether the receiver of this offer will be able to read from the Realm.
        /// </summary>
        public bool MayRead { get; }

        /// <summary>
        /// Gets a value indicating whether the receiver of this offer will be able to write to the Realm.
        /// </summary>
        public bool MayWrite { get; }

        /// <summary>
        /// Gets a value indicating whether the receiver of this offer will be able to manage access rights for others.
        /// </summary>
        public bool MayManage { get; }

        /// <summary>
        /// Gets the expiration date of the offer.
        /// </summary>
        public DateTimeOffset? ExpiresAt { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="PermissionOffer"/> class.
        /// </summary>
        /// <param name="realmUrl">The Realm URL to offer permissions to.</param>
        /// <param name="mayRead">If set to <c>true</c> grants read access.</param>
        /// <param name="mayWrite">If set to <c>true</c> grants write access.</param>
        /// <param name="mayManage">If set to <c>true</c> grants manage access.</param>
        /// <param name="expiresAt">Optional expiration date of the offer. If set to <c>null</c>, the offer doesn't expire.</param>
        public PermissionOffer(string realmUrl, bool mayRead = true, bool mayWrite = false, bool mayManage = false, DateTimeOffset? expiresAt = null)
        {
            RealmPCLHelpers.ThrowProxyShouldNeverBeUsed();
        }
    }
}
