name: centos-docker-container-build
description: Spawn a centos docker container and linux build wrappers
runs:
  using: docker
  env:
    REALM_CMAKE_CONFIGURATION: Release
  image: ${{PROJ_ROOT}}/wrappers/centos.Dockerfile
