name: benchmark-linux
on:
  # To enable running it manually, possibility of adding parameters. It can be run manually only if this file is in master.
  workflow_dispatch:
  push:
env:
  # Branch for Github Pages
  gh-pages-branch: gh-pages
jobs:
  build-wrappers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Check if cache contains wrappers already
        id: wrapper-cache
        uses: actions/cache@v2
        with:
          path: ./wrappers/build/
          key: wrapper-linux-${{hashfiles('./wrappers/**')}}
      - name: Build wrappers Release
        if: steps.wrapper-cache.outputs.cache-hit != 'true'
        run: ./wrappers/build.sh 
  execute-benchmarks:
    needs: [build-wrappers]
    runs-on: ubuntu-latest
    steps:
      - name: Install .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Download previously built wrappers
        id: wrapper-cache
        uses: actions/cache@v2
        with:
          path: ./wrappers/build/
          key: wrapper-linux-${{hashfiles('./wrappers/**')}}
      - name: Check cache hit
        # If there is no cache hit, just fail
        if: steps.wrapper-cache.outputs.cache-hit != 'true'
        run: exit 1
      - name: Print tree
        run: tree /home/runner/work/realm-dotnet/realm-dotnet/Realm/Realm
      - name: Run benchmarks
        run:  |
          dotnet run -p ./Tests/PerformanceTests/ run -c Release --framework net5.0 -- -f * --join
      - name: Save artifacts
        # Not mandatory, but maybe it's good to do it?
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-results
          # Could be put in an environmental variable
          path: ./BenchmarkDotNet.Artifacts/results
