name: release
"on":
  release:
    types:
    - created
jobs:
  publish-to-nuget:
    runs-on: ubuntu-latest
    name: Upload nupkg to nuget
    steps:
    - name: Fetch Realm
      uses: actions/download-artifact@v2
      with:
        name: Realm.${{ needs.build-packages.outputs.package_version }}.nupkg
        path: ${{ github.workspace }}/Realm/packages/
    - name: Fetch Realm.Fody
      uses: actions/download-artifact@v2
      with:
        name: Realm.Fody.${{ needs.build-packages.outputs.package_version }}.nupkg
        path: ${{ github.workspace }}/Realm/packages/
    - name: Upload nupkg
      run: dotnet nuget push "${{ github.workspace }}/Realm/packages/*.nupkg" --skip-duplicate --api-key ${{ secrets.Nuget_Api_Key }} --source https://api.nuget.org/v3/index.json
