name: release
on:
  workflow_dispatch

jobs:
  publish-to-nuget:
    runs-on: windows-latest
    name: Publish nupkg to nuget
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download all artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: main.yml
        branch: ${{ github.ref }}
        path: ${{ github.workspace }}/Realm/packages/
    - name: Extract release notes
      id: extract_release_notes
      run: |
        $changelogContent = Get-Content -Raw -Path "./CHANGELOG.md"
        $output_file = "./RELEASE_NOTES.md"
        $regex = "(?sm)^(## \d{1,2}\.\d{1,2}\.\d{1,2}(?:-[a-zA-Z]*\.\d{1,2})? \(\d{4}-\d{2}-\d{2}\))(.+?)(\n## \d{1,2}\.\d{1,2}\.\d{1,2}(?:-[a-zA-Z]*\.\d{1,2})? \(\d{4}-\d{2}-\d{2}\))"
        $changelogContent -match $regex
        Set-Content -Path $output_file -Value $Matches[2]
        echo "::set-output name=release_notes::$output_file"
    - name: Extract release name
      id: extract_release_ver
      run: |
        $nupkgName = ls "Realm/packages" | Select -expandproperty Name | Select-String Realm.Fody
        $nupkgName -match "(?sm)\d{1,2}\.\d{1,2}\.\d{1,2}(?:-[a-zA-Z]*\.\d{1,2})?"
        $version = $Matches[0]
        echo "::set-output name=release_version::$version"
    - name: Upload to nuget
      run: |
        $release_version = ${{ steps.extract_release_ver.outputs.release_version }}
        echo "Would upload to nuget 'Realm/packages/Realm.Fody.$release_version.nupkg/Realm.Fody.$release_version.nupkg'"
        echo "Would upload to nuget 'Realm/packages/Realm.$release_version.nupkg/Realm.$release_version.nupkg'"
    #     dotnet nuget push "Realm/packages/Realm.Fody.$release_version.nupkg/Realm.Fody.$release_version.nupkg" --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
    #     dotnet nuget push "Realm/packages/Realm.$release_version.nupkg/Realm.$release_version.nupkg" --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
    - name: Create Github Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: Realm/packages/io.realm.unity-${{ steps.extract_release_ver.outputs.release_version }}.tgz/io.realm.unity-${{ steps.extract_release_ver.outputs.release_version }}.tgz
        bodyFile: ${{ steps.extract_release_notes.outputs.release_notes }}
        name: "${{ steps.extract_release_ver.outputs.release_version }} - expand with the main features of this release"
        commit: ${{ github.ref }}
        tag: ${{ steps.extract_release_ver.outputs.release_version }}
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
    - name: Upload docs
      run: |
        Expand-Archive -Path Realm/packages/Docs.zip/Docs.zip -DestinationPath Realm/packages
        py -m pip install s3cmd
        $versions = ${{ steps.extract_release_ver.outputs.release_version }}, "latest"
        Foreach ($ver in $versions)
        {
          s3cmd put --recursive --acl-public --access_key=${{ secrets.DOCS_S3_ACCESS_KEY }} --secret_key=${{ secrets.DOCS_S3_SECRET_KEY }} "${{ github.workspace }}/Realm/packages/_site s3://realm-sdks/realm-sdks/dotnet/$ver/
        }