name: test-core-version
"on":
  pull_request:
    paths:
    - '**.cs'
    - '**.cpp'
    - '**.hpp'
    - '**.csproj'
    - '**CMakeLists.txt'
    - '**.ps1'
    - '**.sh'
    - '**.props'
    - wrappers/realm-core
    - .github/workflows/*.yml
    - '!.github/workflows/main.yml'
    - '!.github/workflows/publish-*.yml'
    - .github/actions/**
env:
  REALM_DISABLE_ANALYTICS: true
  DOTNET_NOLOGO: true
jobs:
  test-stuff:
    runs-on: windows-latest
    name: NuGet
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: false
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Register csc problem matcher
      run: echo "::add-matcher::.github/problem-matchers/csc.json"
    - name: Register msvc problem matcher
      run: echo "::add-matcher::.github/problem-matchers/msvc.json"
    - name: Read Core version
      id: get-core-version
      run: |
        cd wrappers/realm-core
        pkgVersion=$(grep "\bVERSION" dependencies.list | cut -d= -f2)
        echo "core_version=$pkgVersion" >> $GITHUB_OUTPUT
      shell: bash
    - name: Set core version in analytics
      id: set-core-version-analytics
      run: |
        cd Realm/Realm.Weaver/Analytics/
        sed -i 's/_coreVersion \= "\w*"/_coreVersion \= "'"${{ steps.get-core-version.outputs.core-version }}"'"/' Analytics.cs
        cat Analytics.cs
      shell: bash
