name: test-net-framework
"on":
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      BaaSaasApiKey:
        required: false
env:
  REALM_DISABLE_ANALYTICS: true
  DOTNET_NOLOGO: true
jobs:
  run-tests:
    runs-on: windows-latest
    name: .NET Framework
    timeout-minutes: 45
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: false
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Register csc problem matcher
      run: echo "::add-matcher::.github/problem-matchers/csc.json"
    - name: Register msvc problem matcher
      run: echo "::add-matcher::.github/problem-matchers/msvc.json"
    - name: Fetch Realm.PlatformHelpers
      uses: actions/download-artifact@v3
      with:
        name: Realm.PlatformHelpers.${{ inputs.version }}
        path: ${{ github.workspace }}/Realm/packages/
    - name: Fetch Realm
      uses: actions/download-artifact@v3
      with:
        name: Realm.${{ inputs.version }}
        path: ${{ github.workspace }}/Realm/packages/
    - name: Deploy Baas (alternative)
      env:
        apiKey: ${{ secrets.BaaSaasApiKey }}
      if: ${{ env.apiKey }}
      run: dotnet run deploy-apps --baasaas-api-key=${{ secrets.BaaSaasApiKey }} --baas-differentiator=net-framework
      working-directory: Tools/DeployApps
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@0b44c6745b7e81956596964100aadb92d667c497
      if: ${{ runner.os == 'Windows' }}
    - name: Build Tests/Realm.Tests
      run: msbuild Tests/Realm.Tests -p:Configuration=Release -restore -p:RestoreConfigFile=Tests/Test.NuGet.Config -p:UseRealmNupkgsWithVersion=${{ inputs.version }} -p:TargetFramework=net461 -p:RealmTestsStandaloneExe=true
    - name: Run the tests
      run: ./Tests/Realm.Tests/bin/Release/net461/Realm.Tests.exe --result=TestResults.Windows.xml --labels=After --baasaas-api-key=${{ secrets.BaaSaasApiKey}} --baas-differentiator=net-framework
    - name: Publish Unit Test Results
      uses: LaPeste/test-reporter@510caf50a955b1003bec48a6494be4d6537f3a0b
      if: always()
      with:
        name: Results .NET Framework
        path: TestResults.Windows.xml
        reporter: java-junit
        list-suites: failed
        list-tests: failed
        path-replace-backslashes: true
        fail-on-error: false
