name: Wipe all clusters and apps

on:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    name: Wipe all clusters and apps
    steps:
    - uses: realm/ci-actions/mdb-realm/deleteAllClusters@71e2ab925fe61afbda27f9064144c057d3b7c7e1
      with:
        realmUrl: https://realm-qa.mongodb.com
        atlasUrl: https://cloud-qa.mongodb.com
        projectId: ${{ secrets.ATLAS_QA_PROJECT_ID }}
        apiKey: ${{ secrets.ATLAS_QA_PUBLIC_API_KEY }}
        privateApiKey: ${{ secrets.ATLAS_QA_PRIVATE_API_KEY }}
