#@ load("@ytt:template", "template")
#@ load("common.lib.yml", "checkoutCode", "uploadArtifacts", "nugetPackages", "actionDownloadArtifact", "fetchPackageArtifacts")

#@ unityPkgName = "io.realm.unity-${{ inputs.version }}.tgz"

---
name: build-unity
"on":
  workflow_call:
    inputs:
      version:
        type: string
        required: true
env:
  REALM_DISABLE_ANALYTICS: true
  DOTNET_NOLOGO: true
jobs:
  prepare-unity-packages:
    runs-on: windows-latest
    name: Unity
    timeout-minutes: 30
    steps:
      - #@ template.replace(checkoutCode())
      - #@ template.replace(fetchPackageArtifacts("needs.build-packages.outputs.package_version", packages = nugetPackages))
      - name: Build Unity
        run: dotnet run --project Tools/SetupUnityPackage/ -- realm --packages-path Realm/packages --pack
      - #@ uploadArtifacts(unityPkgName, "Realm/Realm.Unity/" + unityPkgName)
      - #@ uploadArtifacts("AssetStorePublisher-${{ inputs.version }}", "Tools/AssetStorePublisher", "${{ (github.event_name != 'pull_request' || contains(github.head_ref, 'release')) && 30 || 1 }}")
      - name: Build Tests
        run: #@ "dotnet run --project Tools/SetupUnityPackage/ -- tests --realm-package Realm/Realm.Unity/" + unityPkgName
      - #@ uploadArtifacts("UnityTests", "Tests/Tests.Unity")
