#@ load("@ytt:template", "template")
#@ load("common.lib.yml", "checkoutCode", "fetchWrapperBinaries", "msBuildMultiple", "readVersionFromPackage", "uploadArtifacts", "actionCache", "nugetPackages", "setupDotnet", "actionSetupAndroid", "setupWorkloads")

#@ def buildDocs():
  - name: Check Docfx cache
    id: check-docfx-cache
    if: inputs.build-docs
    uses: #@ actionCache
    with:
      path: 'C:\docfx'
      key: docfx-2.62.1
  - name: Download docfx
    if: inputs.build-docs && steps.check-docfx-cache.outputs.cache-hit != 'true'
    run: |
      Invoke-WebRequest -Uri https://github.com/dotnet/docfx/releases/download/v2.62.1/docfx-win-x64-v2.62.1.zip -OutFile C:\docfx.zip
      Expand-Archive -Path C:\docfx.zip -DestinationPath C:\docfx
    shell: powershell
  - _: #@ template.replace(setupDotnet("6.0.402", ifCondition = "inputs.build-docs"))
  - name: Build docs
    if: inputs.build-docs
    run: |
      New-Item global.json
      Set-Content global.json '{ "sdk": { "version": "6.0.402" } }'
      C:\docfx\docfx Docs/docfx.json
      Compress-Archive -Path Docs/_site -DestinationPath "Realm/packages/Docs.zip"
  - _: #@ template.replace(uploadArtifacts("Docs.zip", "Realm/packages/Docs.zip"))
    if: inputs.build-docs
#@ end

#@ def uploadPackageArtifacts():
#@ for pkgName in nugetPackages:
#@  finalPkgName = pkgName + ".${{ steps.get-version.outputs.version }}"
  - #@ uploadArtifacts(finalPkgName, "Realm/packages/" + finalPkgName + ".*nupkg")
#@ end
#@ end

#@ def mainPackagePaths():
#@ result = []
#@ for pkg in nugetPackages:
#@   result.append("Realm/" + pkg)
#@ end
#@ return result
#@ end

#@ def setupAndroid():
  - name: Setup Android
    uses: #@ actionSetupAndroid
  - name: Install SDK platform 21
    run: sdkmanager --install "platforms;android-21"
#@ end

---
name: build-packages
"on":
  workflow_call:
    inputs:
      build-docs:
        type: boolean
        required: false
        default: false
    outputs:
      package_version:
        value: ${{ jobs.build-packages.outputs.package_version }}
env:
  REALM_DISABLE_ANALYTICS: true
  DOTNET_NOLOGO: true
jobs:
  build-packages:
    runs-on: windows-latest
    name: NuGet
    outputs:
      package_version: ${{ steps.get-version.outputs.version }}
    timeout-minutes: 30
    steps:
      - #@ template.replace(checkoutCode())
      - #@ template.replace(setupAndroid())
      - #@ setupWorkloads('tvos')
      - name: Set version suffix
        id: set-version-suffix
        #! Build suffix is pr-1234.5 for pr builds or alpha.123 for branch builds.
        run: |
          $suffix = ""
          if ($env:GITHUB_EVENT_NAME -eq "pull_request")
          {
            if (-Not "${{ github.head_ref }}".Contains("release"))
            {
              $suffix = "pr-${{ github.event.number }}.$env:GITHUB_RUN_NUMBER"
            }
          }
          else
          {
            $suffix = "alpha.$env:GITHUB_RUN_NUMBER"
          }
          echo "build_suffix=$suffix" >> $Env:GITHUB_OUTPUT
      - #@ template.replace(fetchWrapperBinaries())
      - #@ template.replace(msBuildMultiple(mainPackagePaths(), target="Pack", PackageOutputPath="${{ github.workspace }}/Realm/packages", VersionSuffix="${{ steps.set-version-suffix.outputs.build_suffix }}"))
      - #@ template.replace(readVersionFromPackage())
      - #@ template.replace(uploadPackageArtifacts())
      - #@ uploadArtifacts("ExtractedChangelog", "Realm/Realm/ExtractedChangelog.md")
      - #@ template.replace(buildDocs())

