#@ load("@ytt:template", "template")
#@ load("common.lib.yml", "checkoutCode", "uploadArtifacts", "actionDownloadArtifact")

---
name: build-packages
"on":
  workflow_call:
    inputs:
      version:
        type: string
        required: true
env:
  REALM_DISABLE_ANALYTICS: true
  DOTNET_NOLOGO: true
jobs:
  setup-unity-tests:
    runs-on: windows-latest
    name: Setup Unity Tests
    steps:
      - #@ template.replace(checkoutCode())
      - name: Fetch Unity package
        uses: #@ actionDownloadArtifact
        with:
          name: io.realm.unity-${{ inputs.version }}.tgz
          path: ${{ github.workspace }}/Realm/packages/
      - name: Build Tests
        run: dotnet run --project Tools/SetupUnityPackage/ -- tests --realm-package Realm/packages/io.realm.unity-${{ inputs.version }}.tgz
      - #@ uploadArtifacts("UnityTests", "Tests/Tests.Unity")
