#@ load("@ytt:template", "template")
#@ load("common.lib.yml", "checkoutCode", "actionCleanupBaaS")

---
name: cleanup-baas
"on":
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      AtlasProjectId:
        required: true
      BaseUrl:
        required: true
      AtlasBaseUrl:
        required: true
      AtlasPublicKey:
        required: true
      AtlasPrivateKey:
        required: true
env:
  REALM_DISABLE_ANALYTICS: true
  DOTNET_NOLOGO: true
jobs:
  cleanup-baas:
    runs-on: ubuntu-latest
    name: Cleanup MDB Realm for ${{ inputs.name }}
    timeout-minutes: 5
    steps:
      - #@ template.replace(checkoutCode(False, False))
      - uses: #@ actionCleanupBaaS
        with:
          projectId: ${{ secrets.AtlasProjectId}}
          realmUrl: ${{ secrets.BaseUrl }}
          atlasUrl: ${{ secrets.AtlasBaseUrl}}
          apiKey: ${{ secrets.AtlasPublicKey}}
          privateApiKey: ${{ secrets.AtlasPrivateKey }}
          differentiator: ${{ inputs.name }}
