#@ load("@ytt:template", "template")
#@ load("common.lib.yml", "checkoutCode", "actionDeployBaaS")

---
name: deploy-baas
"on":
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    outputs:
      clusterName:
        value: ${{ jobs.deploy-baas.outputs.clusterName }}
    secrets:
      AtlasProjectId:
        required: true
      BaseUrl:
        required: true
      AtlasBaseUrl:
        required: true
      AtlasPublicKey:
        required: true
      AtlasPrivateKey:
        required: true
env:
  REALM_DISABLE_ANALYTICS: true
  DOTNET_NOLOGO: true
jobs:
  deploy-baas:
    runs-on: ubuntu-latest
    name: ${{ inputs.name }}
    outputs:
      clusterName: ${{ steps.deploy-mdb-apps.outputs.clusterName }}
    timeout-minutes: 20
    steps:
      - #@ template.replace(checkoutCode(False, False))
      - uses: #@ actionDeployBaaS
        id: deploy-mdb-apps
        with:
          projectId: ${{ secrets.AtlasProjectId}}
          realmUrl: ${{ secrets.BaseUrl }}
          atlasUrl: ${{ secrets.AtlasBaseUrl}}
          apiKey: ${{ secrets.AtlasPublicKey}}
          privateApiKey: ${{ secrets.AtlasPrivateKey }}
          differentiator: ${{ inputs.name }}
