#@ def buildWrappers(cmd, outputVar, intermediateSteps = []):
#@ actualCommand = cmd + " --configuration=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=${{ github.event_name == 'pull_request' && 'ON' || 'OFF' }}"
#@ cacheKey = actualCommand + "-${{hashFiles('./wrappers/**')}}"
#@ cacheCondition = "steps.check-cache.outputs.cache-hit != 'true'"
- name: Checkout code
  uses: actions/checkout@v2
  with:
    submodules: recursive
- name: Check cache
  id: check-cache
  uses: actions/cache@v2
  with:
    path: ./wrappers/build/**
    key: #@ cacheKey
#@ if intermediateSteps:
#@ for step in intermediateSteps:
#@ step["if"] = cacheCondition
- #@ step
#@ end
#@ end
- name: Build wrappers
  if: #@ cacheCondition
  run: #@ actualCommand
- name: Store cache
  if: #@ cacheCondition
  uses: actions/cache@v2
  with:
    path: ./wrappers/build/**
    key: #@ cacheKey
#@ end

#@ def setupVcpkg():
#@   return {"name": "Setup Vcpkg", "uses": "./.github/actions/get-vcpkg-prebuilt"}
#@ end

---
name: build and test
on:
  push:
    branches:
      - main
      - master
  pull_request:
jobs:
  build-wrappers-macos:
    runs-on: macos-latest
    name: Build macOS wrappers
    steps: #@ buildWrappers("./wrappers/build-macos.sh", "wrappers-macos")