#@ load("@ytt:template", "template")
#@ load("@ytt:overlay", "overlay")
#@ load("common.lib.yml", "configuration", "nugetPackages", "checkoutCode", "actionCache", "uploadArtifacts", "actionDownloadArtifact", "actionSetupDotnet", "readVersionFromPackage", "uploadPackagesToSleet", "cleanupWorkspace", "fetchWrapperBinaries", "msBuildMultiple", "dotnetPublish")
#@ load("test.lib.yml", "publishTestsResults")

#@ isRelease = "contains(github.head_ref, 'release')"

#@ ignoreSkippedJobsCondition = "always() && !cancelled() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')"

#@ secret_BaseUrl = "${{ (" + isRelease + " && secrets.REALM_QA_BASE_URL) || secrets.REALM_BASE_URL }}"
#@ secret_AtlasBaseUrl = "${{ (" + isRelease + " && secrets.ATLAS_QA_BASE_URL) || secrets.ATLAS_BASE_URL }}"
#@ secret_AtlasPublicKey = "${{ (" + isRelease + " && secrets.ATLAS_QA_PUBLIC_API_KEY) || secrets.ATLAS_PUBLIC_API_KEY }}"
#@ secret_AtlasPrivateKey = "${{ (" + isRelease + " && secrets.ATLAS_QA_PRIVATE_API_KEY) || secrets.ATLAS_PRIVATE_API_KEY }}"
#@ secret_AtlasProjectId = "${{ (" + isRelease + " && secrets.ATLAS_QA_PROJECT_ID) || secrets.ATLAS_PROJECT_ID }}"

#@ wrappersCacheCondition = "steps.check-cache.outputs.cache-hit != 'true'"
#@ testTimeout = 45

#@ def getJobName(prefix, name):
#@ return prefix + "-" + name.replace(".", "").replace(" ", "-").lower()
#@ end

#@ def deployBaas(name):
#@yaml/text-templated-strings
(@= getJobName("baas", name) @):
  uses: ./.github/workflows/deploy-baas.yml
  with:
    name: #@ name
  secrets:
    AtlasProjectId: #@ secret_AtlasProjectId
    BaseUrl: #@ secret_BaseUrl
    AtlasBaseUrl: #@ secret_AtlasBaseUrl
    AtlasPublicKey: #@ secret_AtlasPublicKey
    AtlasPrivateKey: #@ secret_AtlasPrivateKey
#@ end

#@ def cleanupBaas(name):
#@yaml/text-templated-strings
(@= getJobName("cleanup", name) @):
  uses: ./.github/workflows/cleanup-baas.yml
  needs:
    - #@ getJobName("test", name)
  with:
    name: #@ name
  secrets:
    AtlasProjectId: #@ secret_AtlasProjectId
    BaseUrl: #@ secret_BaseUrl
    AtlasBaseUrl: #@ secret_AtlasBaseUrl
    AtlasPublicKey: #@ secret_AtlasPublicKey
    AtlasPrivateKey: #@ secret_AtlasPrivateKey
#@ end

#@ def runTests(name, runSyncTests = True, additionalSecrets = []):
#@yaml/text-templated-strings
(@= getJobName("test", name) @):
  uses: #@ "./.github/workflows/" + getJobName("test", name) + ".yml"
  if: #@ ignoreSkippedJobsCondition
  needs:
    - build-packages
    #@ if runSyncTests:
    - #@ getJobName("baas", name)
    #@ end
  with:
    version: ${{ needs.build-packages.outputs.package_version }}
    clusterName: #@ "${{ needs." + getJobName("baas", name) + ".outputs.clusterName }}"
  secrets:
    #@ if runSyncTests:
    AtlasProjectId: #@ secret_AtlasProjectId
    BaseUrl: #@ secret_BaseUrl
    AtlasPublicKey: #@ secret_AtlasPublicKey
    AtlasPrivateKey: #@ secret_AtlasPrivateKey
    #@ end
    #@ for secret in additionalSecrets:
    #@yaml/text-templated-strings
    (@= secret @): #@ "${{ secrets." + secret + " }}"
    #@ end
#@ end

#@ def runNetCoreTests(os, framework):
test-net-core:
  if: #@ ignoreSkippedJobsCondition
  needs:
    - build-packages
  uses: #@ "./.github/workflows/test-net-core.yml"
  with:
    version: ${{ needs.build-packages.outputs.package_version }}
    os: #@ os
    framework: #@ framework
#@ end

---

#@ def fetchPackageArtifacts():
#@ for pkg in [ "Realm", "Realm.Fody" ]:
  - name: #@ "Fetch " + pkg
    uses: #@ actionDownloadArtifact
    with:
      name: #@ pkg + ".${{ needs.build-packages.outputs.package_version }}"
      path: ${{ github.workspace }}/Realm/packages/
#@ end
#@ end

#@ def dotnetPublishAndRunTests(projectPath, framework, executeCommand):
#@ properties = {
#@   "AdditionalFrameworks": framework,
#@   "RestoreConfigFile": "Tests/Test.NuGet.Config",
#@   "UseRealmNupkgsWithVersion": "${{ needs.build-packages.outputs.package_version }}"
#@ }
#@
  - #@ template.replace(dotnetPublish(projectPath, framework, properties))
  - name: Run the tests
    run: #@ "${{ steps.dotnet-publish.outputs.executable-path }}/" + executeCommand
#@ end

---
name: main
"on":
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.cs'
      - '**.cpp'
      - '**.hpp'
      - '**.csproj'
      - '**CMakeLists.txt'
      - '**.ps1'
      - '**.sh'
      - '**.props'
      - 'wrappers/realm-core'
      - '.github/workflows/main.yml'
env:
  REALM_DISABLE_ANALYTICS: true
  DOTNET_NOLOGO: true
jobs:
  build-wrappers:
    uses: ./.github/workflows/build-wrappers.yml
  _: #@ template.replace(deployBaas(".NET Framework"))
  _: #@ template.replace(deployBaas("UWP Managed"))
  _: #@ template.replace(deployBaas("Xamarin.macOS"))
  _: #@ template.replace(deployBaas("Xamarin.iOS"))
  _: #@ template.replace(deployBaas("Xamarin.Android"))
  _: #@ template.replace(deployBaas("Code Coverage"))
  build-packages:
    uses: ./.github/workflows/build-packages.yml
    needs:
    - build-wrappers
    with:
      build-docs: ${{ contains(github.head_ref, 'release') }}
  publish-packages-to-sleet:
    runs-on: ubuntu-latest
    name: Publish package to S3
    needs:
    - build-packages
    if: #@ ignoreSkippedJobsCondition + " && github.event_name != 'pull_request'"
    steps:
    - #@ template.replace(checkoutCode(False, False))
    - #@ template.replace(fetchPackageArtifacts())
    - #@ template.replace(uploadPackagesToSleet("needs.build-packages.outputs.package_version", True))
  _: #@ template.replace(runTests(".NET Framework"))
  _: #@ template.replace(runTests("UWP Managed", additionalSecrets = ["Pfx_Password", "Base64_Encoded_Pfx"]))
  _: #@ template.replace(runNetCoreTests("[\"macos-latest\", \"windows-latest\", \"ubuntu-latest\", \"win81\"]", "[\"netcoreapp3.1\", \"net5.0\", \"net6.0\"]"))
  _: #@ template.replace(runTests("Xamarin.macOS"))
  _: #@ template.replace(runTests("Xamarin.iOS"))
  _: #@ template.replace(runTests("Xamarin.Android"))
  run-tests-xunit:
    runs-on: windows-latest
    name: Test xUnit Compatibility
    timeout-minutes: #@ testTimeout
    needs:
    - build-packages
    if: #@ ignoreSkippedJobsCondition + " && github.event_name != 'pull_request'"
    steps:
      - #@ template.replace(checkoutCode())
      - #@ template.replace(fetchPackageArtifacts())
      - uses: #@ actionSetupDotnet
        with:
          dotnet-version: '6.0.x'
      - #@ template.replace(dotnetPublish("Tests/Tests.XUnit", "net6.0", { "RestoreConfigFile": "Tests/Test.NuGet.Config", "UseRealmNupkgsWithVersion": "${{ needs.build-packages.outputs.package_version }}" }))
      - name: Run Tests
        run: dotnet test ${{ steps.dotnet-publish.outputs.executable-path }}/Tests.XUnit.dll --logger GitHubActions
  run-tests-weaver:
    runs-on: windows-latest
    name: Test Weaver
    timeout-minutes: #@ testTimeout
    steps:
      - #@ template.replace(checkoutCode())
      - #@ template.replace(dotnetPublish("Tests/Weaver/Realm.Fody.Tests", "netcoreapp3.1"))
      - name: Run Tests
        run: ${{ steps.dotnet-publish.outputs.executable-path }}/Realm.Fody.Tests --result=TestResults.Weaver.xml --labels=After
      - #@ publishTestsResults("TestResults.Weaver.xml", "Weaver")
  _: #@ template.replace(runTests("Code Coverage"))
  setup-unity-tests:
    runs-on: windows-latest
    name: Setup Unity Tests
    needs:
    - build-packages
    if: #@ ignoreSkippedJobsCondition
    steps:
      - #@ template.replace(checkoutCode())
      - name: Fetch Unity package
        uses: #@ actionDownloadArtifact
        with:
          name: io.realm.unity-${{ needs.build-packages.outputs.package_version }}.tgz
          path: ${{ github.workspace }}/Realm/packages/
      - name: Build Tests
        run: dotnet run --project Tools/SetupUnityPackage/ -- tests --realm-package Realm/packages/io.realm.unity-${{ needs.build-packages.outputs.package_version }}.tgz
      - #@ uploadArtifacts("UnityTests", "Tests/Tests.Unity")
  benchmark-linux:
    name: Benchmark Linux
    needs: build-packages
    runs-on: performance-tests
    if: #@ ignoreSkippedJobsCondition + " && github.event_name != 'pull_request'"
    timeout-minutes: #@ testTimeout
    steps:
      - #@ template.replace(cleanupWorkspace())
      - #@ template.replace(checkoutCode())
      - #@ template.replace(fetchPackageArtifacts())
      - #@ template.replace(dotnetPublishAndRunTests("Tests/Benchmarks/PerformanceTests", "net5.0", "PerformanceTests -f \"*\" --join"))
      - name: Find Results file
        id: find-results-file
        run: |
          cd BenchmarkDotNet.Artifacts/results
          file=$(basename BenchmarkRun*json)
          echo "::set-output name=benchmark-results::$file"
      - name: Publish Benchmark Results
        uses: ./.github/actions/benchmark-uploader
        with:
          realm-token: ${{ secrets.Realm_Token }}
          file: ${{ github.workspace }}/BenchmarkDotNet.Artifacts/results/${{ steps.find-results-file.outputs.benchmark-results }}
          dashboard-path: dashboard.charts
          nuget-package: ${{ github.workspace }}/Realm/packages/Realm.${{ needs.build-packages.outputs.package_version }}.nupkg
      - #@ uploadArtifacts("dashboard.charts", "dashboard.charts", 30)
  _: #@ template.replace(cleanupBaas(".NET Framework"))
  _: #@ template.replace(cleanupBaas("UWP Managed"))
  _: #@ template.replace(cleanupBaas("Xamarin.macOS"))
  _: #@ template.replace(cleanupBaas("Xamarin.iOS"))
  _: #@ template.replace(cleanupBaas("Xamarin.Android"))
  _: #@ template.replace(cleanupBaas("Code Coverage"))
