#@ def buildWrappers(cmd, outputVar, intermediateSteps = []):
#@ actualCommand = cmd + " --configuration=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=${{ github.event_name == 'pull_request' && 'ON' || 'OFF' }}"
- name: Checkout code
  uses: actions/checkout@v2
  with:
    submodules: recursive
- name: Check cache
  id: check-cache
  uses: actions/cache@v2
  with:
    path: ./wrappers/build/**
    cacheKey: #@ actualCommand + "-${{hashFiles('./wrappers/**'))}}"
#@ if intermediateSteps:
#@ for step in intermediateSteps:
- #@ step
#@ end
#@ end
- name: Build wrappers
  if: steps.check-cache.outputs.cache-hit != 'true'
  run: #@ actualCommand
- name: Store cache
  if: steps.check-cache.outputs.cache-hit != 'true'
  uses: actions/cache@v2
  with:
    path: ./wrappers/build/**
    cacheKey: #@ actualCommand + "-${{hashFiles('./wrappers/**'))}}"
#@ end

#@ def setupVcpkg():
#@   return {"name": "Setup Vcpkg", "uses": "./.github/actions/get-vcpkg-prebuilt"}
#@ end

---
name: build and test
on:
  push:
    branches:
      - main
      - master
  pull_request:
jobs:
  build-wrappers-macos:
    runs-on: macos-latest
    name: Build macOS wrappers
    steps: #@ buildWrappers("./wrappers/build-macos.sh", "wrappers-macos")