#@ load("@ytt:template", "template")
#@ load("common.lib.yml", "checkoutCode", "uploadArtifacts", "actionDownloadArtifact", "actionSetupDotnet", "uploadPackagesToSleet", "cleanupWorkspace", "dotnetPublish")
#@ load("test.lib.yml", "publishTestsResults", "dotnetBuildTests")
#@ load("build.lib.yml", "deployBaas", "cleanupBaas", "runTests", "runNetCoreTests", "buildUnity")
---
name: PR Build
"on":
  pull_request:
    paths:
    - '**.cs'
    - '**.cpp'
    - '**.hpp'
    - '**.csproj'
    - '**CMakeLists.txt'
    - '**.ps1'
    - '**.sh'
    - '**.props'
    - wrappers/realm-core
    - .github/workflows/*.yml
    - '!.github/workflows/main.yml'
    - '!.github/workflows/publish-*.yml'
env:
  REALM_DISABLE_ANALYTICS: true
  DOTNET_NOLOGO: true
jobs:
  build-wrappers:
    uses: ./.github/workflows/wrappers.yml
    name: Wrappers
  _: #@ template.replace(deployBaas("Code Coverage"))
  build-packages:
    uses: ./.github/workflows/build-packages.yml
    name: Package
    needs:
    - build-wrappers
    with:
      build-docs: ${{ contains(github.head_ref, 'release') }}
  _: #@ template.replace(buildUnity())
  _: #@ template.replace(runTests(".NET Framework", runSyncTests = False))
  _: #@ template.replace(runTests("UWP Managed", runSyncTests = False, additionalSecrets = ["Pfx_Password", "Base64_Encoded_Pfx"]))
  _: #@ template.replace(runNetCoreTests("[\"macos-latest\", \"windows-latest\", \"ubuntu-latest\", \"win81\"]", "[\"net6.0\"]"))
  _: #@ template.replace(runTests("Xamarin.macOS", runSyncTests = False))
  _: #@ template.replace(runTests("Xamarin.iOS", runSyncTests = False))
  _: #@ template.replace(runTests("Xamarin.Android", runSyncTests = False, additionalSecrets=["AWS_DEVICEFARM_ACCESS_KEY_ID", "AWS_DEVICEFARM_SECRET_ACCESS_KEY", "DEVICEFARM_PROJECT_ARN", "DEVICEFARM_ANDROID_POOL_ARN"]))
  test-weaver:
    uses: ./.github/workflows/test-weaver.yml
    name: Test
  _: #@ template.replace(runTests("Code Coverage"))
  _: #@ template.replace(cleanupBaas("Code Coverage"))
