#@ load("@ytt:template", "template")
#@ load("common.lib.yml", "checkoutCode", "downloadAllArtifacts", "readVersionFromPackage", "uploadPackagesToSleet", "uploadToNpm")

---
name: Publish Prerelease
"on": workflow_dispatch
jobs:
  main:
    runs-on: ubuntu-latest
    name: Publish package to S3
    steps:
    - #@ template.replace(checkoutCode(False, False))
    - #@ template.replace(downloadAllArtifacts("completed"))
    - #@ template.replace(readVersionFromPackage())
    - #@ template.replace(uploadPackagesToSleet())
    - #@ template.replace(uploadToNpm("alpha"))
