#@ load("@ytt:template", "template")
#@ load("@ytt:overlay", "overlay")
#@ load("helpers.lib.yml", "fetchPackageArtifacts")


---
name: release
"on":
  release:
    types:
      - created
jobs:
  publish-to-nuget:
    runs-on: ubuntu-latest
    name: Upload nupkg to nuget
    steps:
      - #@ template.replace(fetchPackageArtifacts())
      - name: Upload nupkg
        run: dotnet nuget push "${{ github.workspace }}/Realm/packages/*.nupkg" --skip-duplicate --api-key ${{ secrets.Nuget_Api_Key }} --source https://api.nuget.org/v3/index.json