#@ load("@ytt:template", "template")
#@ load("common.lib.yml", "checkoutCode", "configuration", "fetchPackageArtifacts")
#@ load("test.lib.yml", "baasTestArgs", "publishTestsResults", "testDefinition", "buildTests", "prepareTest")

---
name: test-macos
_: #@ template.replace(testDefinition())
jobs:
  test-xamarin:
    runs-on: macos-latest
    name: Xamarin.macOS
    timeout-minutes: 45
    steps:
      - #@ template.replace(prepareTest())
      - #@ template.replace(buildTests("Tests/Tests.XamarinMac"))
      - name: Run the tests
        run: #@ "Tests/Tests.XamarinMac/bin/" + configuration + "/Tests.XamarinMac.app/Contents/MacOS/Tests.XamarinMac --headless --result=${{ github.workspace }}/TestResults.XamarinMac.xml --labels=All" + baasTestArgs("xamarinmacos")
      - #@ publishTestsResults("TestResults.XamarinMac.xml", "Xamarin.macOS")
  test-maui:
    runs-on: macos-12
    name: Maui.MacCatalyst
    timeout-minutes: 45
    steps:
      - #@ template.replace(checkoutCode())
      - #@ template.replace(fetchPackageArtifacts())
      - name: Setup workloads
        run: |
          dotnet workload install maui
      - name: Build the tests
        run: #@ "dotnet build Tests/Tests.Maui -c " + configuration + " -f net6.0-maccatalyst -p:RestoreConfigFile=Tests/Test.NuGet.Config -p:UseRealmNupkgsWithVersion=${{ inputs.version }}"
      - name: Run the tests
        run: #@ "Tests/Tests.Maui/bin/" + configuration + "/net6.0-maccatalyst/maccatalyst-x64/Tests.Maui.app/Contents/MacOS/Tests.Maui --headless --result=${{ github.workspace }}/TestResults.MacCatalyst.xml --labels=All" + baasTestArgs("maccatalyst")
      - #@ publishTestsResults("TestResults.MacCatalyst.xml", "Maui.MacCatalyst")