#@ load("common.lib.yml", "uploadArtifacts", "actionDownloadArtifact")

#@ unityPkgName = "io.realm.unity-${{ inputs.version }}.tgz"

---
name: test-unity
"on":
  workflow_call:
    inputs:
      version:
        type: string
        required: true
env:
  REALM_DISABLE_ANALYTICS: true
  DOTNET_NOLOGO: true
jobs:
  build-tests:
    runs-on:
      - unity
      - ${{ matrix.testData.os }}
    name: Build Unity ${{ matrix.testData.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        settings: [ Mono-Net4 ]
        testData:
          #! - os: linux
          #!  platform: Linux64
          - os: windows
            platform: Windows64
    steps:
      - name: Fetch Unity Package
        uses: #@ actionDownloadArtifact
        with:
          name: #@ unityPkgName
          path: Realm/Realm.Unity
      - name: Fetch Unity Tests
        uses: #@ actionDownloadArtifact
        with:
          name: UnityTests
          path: Tests/Tests.Unity
      - run: echo $PATH
        if: matrix.testData.os == 'linux'
      - name: Build Unity Tests
        run: |
          unity-editor -runTests -batchmode -projectPath ${{ github.workspace }}/Tests/Tests.Unity -testPlatform Standalone${{ matrix.testData.platform }} -testSettingsFile ${{ github.workspace }}/Tests/Tests.Unity/.TestConfigs/${{ matrix.settings }}.json -logFile ${{ matrix.testData.os == 'windows' && 'build.log' || '-'}}
          ${{ matrix.testData.os == 'windows' && 'cat build.log' || ''}}
      - #@ uploadArtifacts("UnityTestsRunner.${{ matrix.testData.os }}", "Tests/Tests.Unity/Player_Standalone${{ matrix.testData.platform }}_${{ matrix.settings }}/")

  #! run-tests-linux:
  #!   runs-on: ubuntu-latest
  #!   name: Unity Linux
  #!   timeout-minutes: 30
  #!   needs:
  #!     - build-tests
  #!   steps:
  #!     - name: Download Test Runner
  #!       uses: #@ actionDownloadArtifact
  #!       with:
  #!         name: UnityTestsRunner.linux
  #!         path: TestRunner
  #!     - name: Run Tests
  #!       run: |
  #!         ./TestRunner/PlayerWithTests -logFile -

  run-tests-windows:
    runs-on: windows-latest
    name: Unity Windows
    timeout-minutes: 30
    needs:
      - build-tests
    steps:
      - name: Download Test Runner
        uses: #@ actionDownloadArtifact
        with:
          name: UnityTestsRunner.windows
          path: TestRunner
      - name: Run Tests
        run: |
          tree
          ${{ github.workspace }}\TestRunner\PlayerWithTests.exe -logFile test.log
          cat test.log
        shell: powershell
