#@ load("@ytt:template", "template")
#@ load("common.lib.yml", "checkoutCode", "configuration")
#@ load("test.lib.yml", "fetchPackageArtifacts", "baasTestArgs", "publishTestsResults", "testDefinition", "buildTests")

---
name: test-xamarinmacos
_: #@ template.replace(testDefinition())
jobs:
  run-tests:
    runs-on: macos-latest
    name: Xamarin.macOS
    timeout-minutes: 45
    steps:
      - #@ template.replace(checkoutCode())
      - #@ template.replace(fetchPackageArtifacts())
      - #@ template.replace(buildTests("Tests/Tests.XamarinMac"))
      - name: Run the tests
        run: #@ "Tests/Tests.XamarinMac/bin/" + configuration + "/Tests.XamarinMac.app/Contents/MacOS/Tests.XamarinMac --headless --result=${{ github.workspace }}/TestResults.macOS.xml --labels=All" + baasTestArgs
      - #@ publishTestsResults("TestResults.macOS.xml", "Xamarin.macOS")
