#@ load("common.lib.yml", "uploadArtifacts", "actionDownloadArtifact")

#@ unityPkgName = "io.realm.unity-${{ inputs.version }}.tgz"

---
name: test-unity
"on":
  workflow_call:
    inputs:
      version:
        type: string
        required: true
env:
  REALM_DISABLE_ANALYTICS: true
  DOTNET_NOLOGO: true
jobs:
  build-unity-tests:
    runs-on: [linux, unity]
    name: Build Unity Linux
    timeout-minutes: 30
    steps:
      - name: Fetch Unity Package
        uses: #@ actionDownloadArtifact
        with:
          name: #@ unityPkgName
          path: Realm/Realm.Unity
      - name: Fetch Unity Tests
        uses: #@ actionDownloadArtifact
        with:
          name: UnityTests
          path: Tests/Tests.Unity
      - name: Build Unity Tests
        run: |
          unity-editor -runTests -batchmode \
            -projectPath Tests/Tests.Unity \
            -testPlatform StandaloneOSX \
            -testSettingsFile ${{ github.workspace }}/Tests/Tests.Unity/.TestConfigs/Mono-Net4.json \
            -logFile -
      - #@ uploadArtifacts("UnityTestsRunner.Linux", "Tests/Tests.Unity/Player**/*")
  run-unity-tests:
    runs-on: ubuntu-latest
    name: Unity Linux
    timeout-minutes: 30
    steps:
      - name: Download Test Runner
        uses: #@ actionDownloadArtifact
        with:
          name: UnityTestsRunner.Linux
          path: TestRunner
      - name: Run Tests
        run: |
          ./PlayerWithTests -logFile -

