#@ load("@ytt:template", "template")
#@ load("common.lib.yml", "checkoutCode", "fetchWrapperBinaries", "msBuildMultiple", "readVersionFromPackage", "readCoreVersion", "uploadArtifacts", "actionCache", "nugetPackages", "setupDotnet")

#@ def setCoreVersionAnalytics():
  - name: Set core version in analytics
    id: set-core-version-analytics
    run: |
      cd Realm/Realm.Weaver/Analytics/
      sed -i 's/_coreVersion \= "\w*"/_coreVersion \= "'"${{ steps.get-core-version.outputs.core-version }}"'"/' Analytics.cs
      cat Analytics.cs
    shell: bash
#@ end


---
name: test-core-version
"on":
  pull_request:
    paths:
    - '**.cs'
    - '**.cpp'
    - '**.hpp'
    - '**.csproj'
    - '**CMakeLists.txt'
    - '**.ps1'
    - '**.sh'
    - '**.props'
    - wrappers/realm-core
    - .github/workflows/*.yml
    - '!.github/workflows/main.yml'
    - '!.github/workflows/publish-*.yml'
    - .github/actions/**
env:
  REALM_DISABLE_ANALYTICS: true
  DOTNET_NOLOGO: true
jobs:
  test-stuff:
    runs-on: windows-latest
    name: NuGet
    timeout-minutes: 30
    steps:
      - #@ template.replace(checkoutCode("recursive", False))
      - #@ template.replace(readCoreVersion())
      - #@ template.replace(setCoreVersionAnalytics())