#@ load("@ytt:template", "template")
#@ load("common.lib.yml", "checkoutCode")
#@ load("test.lib.yml", "fetchPackageArtifacts", "baasTestArgs", "publishTestsResults", "testDefinition", "buildTests", "wovenClassesBuildTests")

---
name: test-woven-classes
_: #@ template.replace(testDefinition())
jobs:
  run-tests:
    runs-on: windows-latest
    name: Woven classes
    timeout-minutes: 45
    steps:
      - #@ template.replace(checkoutCode())
      - #@ template.replace(fetchPackageArtifacts())
      - #@ template.replace(wovenClassesBuildTests("Tests/Realm.Tests", "net7.0", "win-x64"))
      - name: Run the tests
        run: #@ "${{ steps.dotnet-publish.outputs.executable-path }}/Realm.Tests --result=TestResults.WovenClasses.xml --labels=After" + baasTestArgs("weaved-classes")
      - #@ publishTestsResults("TestResults.WovenClasses.xml", "Woven classes")
