#@ load("@ytt:template", "template")
#@ load("common.lib.yml", "checkoutCode", "configuration")
#@ load("test.lib.yml", "baasTestArgs", "publishTestsResults", "testDefinition", "buildTests", "prepareTest")

---
name: test-net-framework
_: #@ template.replace(testDefinition())
jobs:
  run-tests:
    runs-on: windows-latest
    name: .NET Framework
    timeout-minutes: 45
    steps:
      - #@ template.replace(prepareTest())
      - #@ template.replace(buildTests("Tests/Realm.Tests", TargetFramework="net461", RealmTestsStandaloneExe="true"))
      - name: Run the tests
        run: #@ "./Tests/Realm.Tests/bin/" + configuration + "/net461/Realm.Tests.exe --result=TestResults.Windows.xml --labels=After" + baasTestArgs("net-framework")
      - #@ publishTestsResults("TestResults.Windows.xml", ".NET Framework")
