#@ load("@ytt:template", "template")
#@ load("common.lib.yml", "checkoutCode")
#@ load("test.lib.yml", "fetchPackageArtifacts", "baasTestArgs", "publishTestsResults", "testDefinition", "buildTests", "dotnetBuildTests")

---
name: test-console
_: #@ template.replace(testDefinition(additionalInputs = [ "framework"]))
jobs:
  test-console:
    runs-on: ${{ matrix.os.runner }}
    name: ${{ matrix.framework }}, ${{ matrix.os.runtime }}
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        os:
        - runner: windows-latest
          runtime: win-x64
        - runner: ubuntu-latest
          runtime: linux-x64
        - runner: macos-latest
          runtime: osx-x64
        - runner: win81
          runtime: win-x64
        framework: ${{ fromJson(inputs.framework) }}
        include:
        - framework: net461
          os:
            runner: windows-latest
            runtime: win-x64
    steps:
      - #@ template.replace(checkoutCode())
      - name: Cleanup Workspace
        run: git clean -fdx
      - #@ template.replace(fetchPackageArtifacts())
      - #@ template.replace(dotnetBuildTests("Tests/Tests.Console", "${{ matrix.framework }}", "${{ matrix.os.runtime }}"))
      - name: Run the tests
        run: #@ "${{ steps.dotnet-publish.outputs.executable-path }}/Tests.Console --result=TestResults.xml --labels=After" + baasTestArgs("net-core-${{ matrix.runner }}-${{ matrix.runtime }}")
      - #@ publishTestsResults("TestResults.xml", ".NET (${{ matrix.os.runner }}, ${{ matrix.framework }})")
