#@ load("@ytt:template", "template")
#@ load("common.lib.yml", "checkoutCode", "configureAWSCredentials", "fetchPackageArtifacts", "setupWorkloads", "setupJDK")
#@ load("test.lib.yml", "baasTestArgs", "publishTestsResults", "testDefinition", "buildTests", "prepareTest")

---
name: test-android
_: #@ template.replace(testDefinition(additionalSecrets=["AWS_DEVICEFARM_ACCESS_KEY_ID", "AWS_DEVICEFARM_SECRET_ACCESS_KEY", "DEVICEFARM_PROJECT_ARN", "DEVICEFARM_ANDROID_POOL_ARN"]))
jobs:
  test-xamarin:
    runs-on: windows-latest
    name: Xamarin.Android
    timeout-minutes: 60
    steps:
      - #@ setupJDK()
      - #@ template.replace(prepareTest("android"))
      - #@ template.replace(buildTests("Tests/Tests.Android", target="SignAndroidPackage", AndroidUseSharedRuntime="False", EmbedAssembliesIntoApk="True"))
      - #@ template.replace(configureAWSCredentials("AWS_DEVICEFARM_ACCESS_KEY_ID", "AWS_DEVICEFARM_SECRET_ACCESS_KEY", "us-west-2"))
      - name: Run the tests
        uses: ./.github/actions/run-android-device-farm-test
        id: run_tests
        #@yaml/text-templated-strings
        with:
          apk-path: ${{ github.workspace }}/Tests/Tests.Android/bin/Release/io.realm.xamarintests-Signed.apk
          app-id: io.realm.xamarintests
          project-arn: ${{ secrets.DEVICEFARM_PROJECT_ARN }}
          device-pool-arn: ${{ secrets.DEVICEFARM_ANDROID_POOL_ARN }}
          arguments: (@= baasTestArgs('android') @)
      - #@ publishTestsResults("${{ steps.run_tests.outputs.test-results-path }}", "Xamarin.Android")
  test-maui:
    runs-on: windows-latest
    name: Maui.Android
    timeout-minutes: 60
    steps:
      - #@ template.replace(checkoutCode())
      - #@ template.replace(fetchPackageArtifacts())
      - #@ template.replace(setupWorkloads())
      - #@ setupJDK()
      - name: Build the tests
        run: #@ "dotnet publish Tests/Tests.Maui -c Release -f net8.0-android -p:RestoreConfigFile=Tests/Test.NuGet.Config -p:UseRealmNupkgsWithVersion=${{ inputs.version }}"
      - #@ template.replace(configureAWSCredentials("AWS_DEVICEFARM_ACCESS_KEY_ID", "AWS_DEVICEFARM_SECRET_ACCESS_KEY", "us-west-2"))
      - name: Run the tests
        uses: ./.github/actions/run-android-device-farm-test
        id: run_tests
        with:
          apk-path: ${{ github.workspace }}/Tests/Tests.Maui/bin/Release/net8.0-android/publish/io.realm.mauitests-Signed.apk
          app-id: io.realm.mauitests
          project-arn: ${{ secrets.DEVICEFARM_PROJECT_ARN }}
          device-pool-arn: ${{ secrets.DEVICEFARM_ANDROID_POOL_ARN }}
      - #@ publishTestsResults("${{ steps.run_tests.outputs.test-results-path }}", "Maui.Android")