#@ load("@ytt:template", "template")
#@ load("common.lib.yml", "checkoutCode", "actionSetupDotnet")
#@ load("test.lib.yml", "fetchPackageArtifacts", "baasTestArgs", "publishTestsResults", "testDefinition", "buildTests", "weavedClassesBuildTests")

---
name: test-weaved-classes
_: #@ template.replace(testDefinition())
jobs:
  run-tests:
    runs-on: windows-latest
    name: Weaved classes
    timeout-minutes: 45
    steps:
      - #@ template.replace(checkoutCode())
      - name: Cleanup Workspace
        run: git clean -fdx
      - uses: #@ actionSetupDotnet
        with:
          dotnet-version: '6.0.x'
      - #@ template.replace(fetchPackageArtifacts())
      - #@ template.replace(weavedClassesBuildTests("Tests/Realm.Tests", "net6.0", "win-x64"))
      - name: Run the tests
        run: #@ "${{ steps.dotnet-publish.outputs.executable-path }}/Realm.Tests --result=TestResults.WeavedClasses.xml --labels=After" + baasTestArgs("weaved-classes")
      - #@ publishTestsResults("TestResults.WeavedClasses.xml", "Weaved classes")
