#@ load("@ytt:template", "template")
#@ load("common.lib.yml", "checkoutCode", "configuration")
#@ load("test.lib.yml", "fetchPackageArtifacts", "baasTestArgs", "publishTestsResults", "testDefinition", "buildTests")

---
name: test-net-framework
_: #@ template.replace(testDefinition())
jobs:
  run-tests:
    runs-on: windows-latest
    name: .NET Framework
    timeout-minutes: 45
    steps:
      - #@ template.replace(checkoutCode())
      - #@ template.replace(fetchPackageArtifacts())
      - #@ template.replace(buildTests("Tests/Tests.NetCore", TargetFramework="net461"))
      - name: Run the tests
        run: #@ "./Tests/Tests.NetCore/bin/" + configuration + "/net461/Tests.NetCore.exe --result=TestResults.Windows.xml --labels=After" + baasTestArgs("net-framework")
      - #@ publishTestsResults("TestResults.Windows.xml", ".NET Framework")
