#@ load("@ytt:template", "template")
#@ load("common.lib.yml", "checkoutCode", "dotnetPublish", "setupWorkloads")
#@ load("test.lib.yml", "publishTestsResults")

---
name: test-weaver
"on":
  workflow_call:
env:
  REALM_DISABLE_ANALYTICS: true
  DOTNET_NOLOGO: true
jobs:
  run-tests-weaver:
    strategy:
      matrix:
        os:
        - runner: windows-latest
          runtime: win-x64
        - runner: ubuntu-latest
          runtime: linux-x64
        - runner: macos-latest
          runtime: osx-x64
    runs-on: ${{ matrix.os.runner }}
    name: Weaver
    timeout-minutes: 30
    steps:
      - #@ template.replace(checkoutCode())
      - #@ template.replace(setupWorkloads("android ${{ (matrix.os.runner != 'ubuntu-latest' && 'tvos ios maccatalyst') || '' }}"))
      - #@ template.replace(dotnetPublish("Tests/Weaver/Realm.Fody.Tests", "net6.0", "${{ matrix.os.runtime }}"))
      - name: Run Tests
        run: ${{ steps.dotnet-publish.outputs.executable-path }}/Realm.Fody.Tests --result=TestResults.Weaver.xml --labels=After
      - #@ publishTestsResults("TestResults.Weaver.xml", "Weaver ${{ matrix.os.runtime }}")
