#@ load("@ytt:template", "template")
#@ load("common.lib.yml", "checkoutCode", "uploadArtifacts")
#@ load("test.lib.yml", "baasTestArgs", "publishTestsResults", "testDefinition", "buildTests", "dotnetBuildTests", "prepareTest")

---
name: test-net-core
_: #@ template.replace(testDefinition(additionalInputs = [ "framework"]))
jobs:
  run-tests:
    runs-on: ${{ matrix.os.runner }}
    name: ${{ matrix.framework }}, ${{ (matrix.os.runner == 'win81' && 'win81') || matrix.os.runtime }}
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        os:
        - runner: windows-latest
          runtime: win-x64
        - runner: ubuntu-latest
          runtime: linux-x64
        - runner: macos-latest
          runtime: osx-x64
        framework: ${{ fromJson(inputs.framework) }}
        include:
        - framework: net7.0
          os:
            runner: macos-arm
            runtime: osx-arm64
        - framework: net7.0
          os:
            runner: win81
            runtime: win-x64

    steps:
      - #@ template.replace(prepareTest(cleanupWorkspace = True))
      - #@ template.replace(dotnetBuildTests("Tests/Realm.Tests", "${{ matrix.framework }}", "${{ matrix.os.runtime }}"))
      - name: Run the tests
        run: #@ "${{ steps.dotnet-publish.outputs.executable-path }}/Realm.Tests --result=TestResults.xml --labels=After" + baasTestArgs("net-core-${{ matrix.runner }}-${{ matrix.runtime }}")
      - #@ publishTestsResults("TestResults.xml", ".NET (${{ matrix.os.runner }}, ${{ matrix.framework }})")
